MP-594
Nictiz/Nictiz-R4-MedicationProcess pull request #39
Opened 2023-10-25 17:46 UTC by LuudSlagter

2023-10-26 12:53 UTC, weteringac requested changes

2023-10-26 12:53 UTC, weteringac commented on SearchParameters/SearchParameter-period-of-use.xml
"even if these are authored outside the PeriodOfUse that is being searched on"

even if these have a period of use outside the ...

2023-10-26 12:53 UTC, weteringac commented on SearchParameters/SearchParameter-period-of-use.xml
Ik vind deze uitleg super helder, maar mis daar dat het per MBH moet. Het staat daarboven wel, maar ik zou het hier nogmaals noemen:

For this all MedicationRequest and MedicationDispense resources wherein the [ext-StopType](http://nictiz.nl/fhir/StructureDefinition/ext-StopType) extension is present should be considered, before including (for each pharmaceutical treatment) only the latest one based on the value of `MedicationRequest.authoredOn` and the [ext-AdministrationAgreement.AdministrationAgreementDateTime](http://nictiz.nl/fhir/StructureDefinition/ext-AdministrationAgreement.AdministrationAgreementDateTime) extension, respectively."

2023-10-27 08:44 UTC, LuudSlagter commented on SearchParameters/SearchParameter-period-of-use.xml
Fixed!

2023-10-27 08:45 UTC, LuudSlagter commented on SearchParameters/SearchParameter-period-of-use.xml
Ik heb '(for each pharmaceutical treatment)' vervangen door ', for each pharmaceutical treatment,' (dit was ook feedback van Jorn).

2023-10-27 15:30 UTC, weteringac requested changes

2023-10-27 15:30 UTC, weteringac commented on SearchParameters/SearchParameter-period-of-use.xml
Er staat nog steeds:

even if these are authored outside the PeriodOfUse that is being searched on

Het gaat niet wanneer geregistreerd, maar wanneer het gebruik is.

2023-10-30 06:06 UTC, LuudSlagter commented on SearchParameters/SearchParameter-period-of-use.xml
Er staat nu 'even if these have a period of use outside the PeriodOfUse that is being searched on', toch?

2023-10-30 07:24 UTC, weteringac approved these changes

2023-10-31 11:06 UTC, merged